/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ayubmalik.web.alchemy;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

import ayubmalik.web3.alchemy.Library;

class LibraryTest {

    @Test
    void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
